use std::fs::File;
use std::io;

// test-data/object.npy is generated by this Python code:
//
// import numpy as np
// np.save('test-data/object.npy', {})

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut file = io::BufReader::new(File::open("test-data/object.npy")?);

    let header = npyz::NpyHeader::from_reader(&mut file).unwrap();

    let npyz::DType::Plain(type_str) = header.dtype() else {
        panic!()
    };
    assert_eq!(type_str.type_char(), npyz::TypeChar::Object);

    let value = serde_pickle::value_from_reader(&mut file, Default::default());
    eprintln!("{:?}", value?);

    Ok(())
}
