use std::io;
use std::fs::File;

use serde_pickle;

// test-data/pickle.npy is generated by this Python code:
//
// import numpy as np
// a = np.array([
//     [1, 3.5, "number"],
//     [{}, {}, None],
// ], dtype=object)
// np.save('test-data/pickle.npy', a)

fn main() -> io::Result<()> {
    let file = io::BufReader::new(File::open("test-data/pickle.npy")?);
    let npy = npyz::NpyFile::new(file)?;

    assert_eq!(npy.shape(), &[2, 3]);
    println!("DType: {}", npy.dtype().descr());
    println!("Shape: {:?}", npy.shape());
    println!("Strides: {:?}", npy.strides());

    // When an array involves objects, the **entire** array is written in a single pickle.
    // npyz can't help us any further here.
    let file = npy.into_inner();
    let de_options = Default::default();
    let value = serde_pickle::value_from_reader(file, de_options).map_err(pickle_err_to_io_err)?;

    // The pickled value begins with a bunch of array metadata that's tough to make sense of,
    // but at the end you will see the data, a flat list of the objects written by the python
    // snippet at the top of this file.
    println!("Pickled value: {:#?}", value);

    Ok(())
}

fn pickle_err_to_io_err(error: serde_pickle::Error) -> io::Error {
    match error {
        serde_pickle::Error::Io(e) => e,
        error => io::Error::new(io::ErrorKind::Other, error.to_string()),
    }
}
