use std::fs::File;
use std::io;

use npyz::NpyReader;

// test-data/plain.npy is generated by this Python code:
//
// import numpy as np
// a = np.array([1, 3.5, -6, 2.3])
// np.save('test-data/plain.npy', a)

fn main() -> io::Result<()> {
    let file = io::BufReader::new(File::open("test-data/plain.npy")?);

    let reader: NpyReader<f64, _> = NpyReader::new(file)?;
    for arr in reader {
        eprintln!("{:?}", arr?);
    }
    Ok(())
}
